language: cpp

matrix:
  include:
    - name: "Linux (gcc)"
      os: linux
      compiler: gcc
      script:
        - cmake --build . --target test

    - name: "Linux (clang)"
      os: linux
      compiler: clang
      script:
        - cmake --build . --target test

    - name: "OSX"
      os: osx
      script:
        - cmake --build . --target test

    - name: "Windows"
      os: windows
      script:
        - cmake --build . --target RUN_TESTS

  allow_failures:
    - os: windows
  fast_finish: true

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

notifications:
  email: false
